Add optional parameter stripe-account with test coverage
bennypowers/stripe-elements pull request #84
Opened 2022-06-02 08:55 UTC by whiteancient

2022-06-02 09:56 UTC, bennypowers requested changes
a few small nits

2022-06-02 09:56 UTC, bennypowers commented on src/StripeBase.ts
> +        const options = stripeAccount ? { 'stripeAccount': stripeAccount } : {};
```suggestion
        const options = { stripeAccount };
```

2022-06-02 09:56 UTC, bennypowers commented on test/mock-stripe/index.ts
> +  STRIPE_ACCOOUNT = 'acct_XXXXXXXXXXX',
```suggestion
  STRIPE_ACCOUNT = 'acct_XXXXXXXXXXX',
```

2022-06-02 09:56 UTC, bennypowers commented on test/stripe-elements.test.ts
> +        beforeEach(Helpers.setupWithPublishableKeyAndStripeAccount(Keys.PUBLISHABLE_KEY, Keys.STRIPE_ACCOOUNT));
```suggestion
        beforeEach(Helpers.setupWithPublishableKeyAndStripeAccount(Keys.PUBLISHABLE_KEY, Keys.STRIPE_ACCOUNT));
```

2022-06-02 09:56 UTC, bennypowers commented on test/stripe-payment-request.test.ts
> +          it('reinitializes stripe', function() { expect(element.stripe).to.be.ok.and.not.equal(Helpers.initialStripe); });
```suggestion
          it('reinitializes stripe', function() { expect(element.stripe).to.be.ok.and.not.deep.equal(Helpers.initialStripe); });
```

2022-06-02 09:56 UTC, bennypowers commented on docs/index.md
> +For use with Stripe Connect, you can provide the optional `stripe-account` attribute set to the account ID of the connected account.
```suggestion
For use with [Stripe Connect](https://stripe.com/docs/js/initializing#init_stripe_js-options-stripeAccount), you can provide the optional `stripe-account` attribute set to the account ID of the connected account.
```

2022-06-02 10:14 UTC, whiteancient commented
All your change requests committed :)

2022-06-02 10:18 UTC, merged

2022-06-02 10:18 UTC, bennypowers commented
Thank you for the contribution

2022-06-02 10:19 UTC, whiteancient commented
Thanks for the support to get it through!

2022-06-21 08:32 UTC, bennypowers commented
This was released with 3.2.0